### ISSUE TITLE
MapAlignerIdentification  step error.

### ISSUE THREAD

**Issue by ATPs** [nf-core/mhcquant#115]
```
-[nf-core/mhcquant] Pipeline completed with errors-
Error executing process > 'align_ids'

Caused by:
  Process `align_ids` terminated with an error exit status (8)

Command executed:

  MapAlignerIdentification -in train_sample_66_ms_run_4.mzML_idx_fdr_filtered.idXML \
                           -trafo_out train_sample_66_ms_run_4.mzML_idx_fdr_filtered.trafoXML \
                           -model:type linear \
                           -algorithm:max_rt_shift 300

Command exit status:
  8

Command output:
  Progress of 'loading input files':

  -- done [took 0.00 s (CPU), 0.01 s (Wall)] --
  Warning: Value of parameter 'min_run_occur' (here: 2) is higher than the number of runs incl. reference (here: 1). Using 1 instead.
  Progress of 'aligning maps':
  Error: Unexpected internal error (No reference RT information left after filtering)

Command wrapper:
  Progress of 'loading input files':

  -- done [took 0.00 s (CPU), 0.01 s (Wall)] --
  Warning: Value of parameter 'min_run_occur' (here: 2) is higher than the number of runs incl. reference (here: 1). Using 1 instead.
  Progress of 'aligning maps':
  Error: Unexpected internal error (No reference RT information left after filtering)

Work dir:
  /projectsp/f_jx76_1/xiaolong/temp/MSV000082648/20200326comet/train_sample_66_ms_run_4.mod1/work/5e/dce3d87a55eac31852aad2c4ad3398

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

```

**Comment by ATPs** [comment]
maybe the input mzML is not standard format?

**Comment by ATPs** [comment]
Also, I tried to run the components one by one till percolator step. I changed the file to mztab format myself, but I didn’t see the FDR column. If I change the file format and run crux percolator, I got zero peptides. 

The file format are so mysterious for me. Too hard to get it work.

**Comment by Leon-Bichmann** [comment]
Hi Xiaolong, thanks for trying to use mhcquant.

**Comment by Leon-Bichmann** [comment]
About the FDR column - the q-value is annotated in the "best_search_engine_score[1]" column of the mzTab file.

**Comment by ATPs** [comment]
> About the FDR column - the q-value is annotated in the "best_search_engine_score[1]" column of the mzTab file.

Thank you so much for your reply. I will check again. I am using data from others. I am not sure if there is replicate for the same sample. 

I used run nextflow components step by step. For the input file of percolator, I run percolator myself but get quite  different result. I guess it is not related with this tool. But I suppose that they are the same or at least very similar. So the openms PercolatorAdapter have some hidden function other than using percolator directly?

I mean for this search, the decoy sequence might include quite some overlap with target. So this will cause some problem?


In my case,  if I use comet and then use percolator directly, the number of peptide with fdr <0.01 is much smaller than mhcquant. What might be the cause of the? I also tried crux percolator and newest version of percolator on the same data, but get different result.

Do you have any suggestions? Thank you so much!

**Comment by ATPs** [comment]
I am really struggling 😂😂😂，thank you, Leon.

**Comment by Leon-Bichmann** [comment]
No, worries.

So, if there is only a single replicate I'm afraid you won't be able to use mhcquant.

About the number of peptide identifications you get when running each step separately:  That can depend on the parameters you set and which version of the respective tool you are using. The OpenMS Percolator Adapter might indeed have some default parameters that are different from the standalone percolator tool.

That's why we try to be reproducible with this pipeline using only particular versions in one container.

Default parameters in mhcquant are set for high resolution orbitrap data. In case your data comes from another instrumental setting you would need to adapt them as well.

**Comment by ATPs** [comment]
Thank you for your rely, Leon. I guess I will try to read more about different components of openms. It will be vey helpful if there is a more detailed description about the function of each step. But thank you a lot for this great tool!

**Comment by ATPs** [comment]
I will read your paper more carefully to see the design idea. By the way, I like your name, for the movie. Stay safe! Best! I hope you are good and I may want to ask you for help in the futures.

**Comment by ATPs** [comment]
Hi, Leon. Just to make sure. I convert the step12 output, filter by percolator q-value to mzTab. There is no column "best_search_engine_score[1]". Below is the columns I saw. so the column "search_engine_score[1] " is the FDR value?

```
PSH                                                                              PSM
sequence                                                                   ATTSNTVSK
PSM_ID                                                                             0
accession                                                      sp|Q6NZI2|CAVN1_HUMAN
unique                                                                             1
database                                              AUP000005640.fasta_decoy.fasta
database_version                                                                 NaN
search_engine                                                          [, , Comet, ]
search_engine_score[1]                                                    0.00308772
modifications                                                                    NaN
retention_time                                                                 619.1
charge                                                                             2
exp_mass_to_charge                                                           454.739
calc_mass_to_charge                                                          454.738
spectra_ref                        ms_run[1]:controllerType=0 controllerNumber=1 ...
pre                                                                                H
post                                                                               L
start                                                                            101
end                                                                              109
opt_global_modified_sequence                                               ATTSNTVSK
opt_global_COMET:IonFrac                                                      0.6875
opt_global_COMET:deltCn                                                      0.23026
opt_global_COMET:deltLCn                                                    0.347045
opt_global_COMET:lnExpect                                                   -2.92248
opt_global_COMET:lnNumSP                                                     11.0222
opt_global_COMET:lnRankSP                                                          0
opt_global_MS:1001491                                                     0.00308772
opt_global_MS:1001492                                                       0.329372
opt_global_MS:1001493                                                      0.0507086
opt_global_MS:1002252                                                          2.115
opt_global_MS:1002253                                                          0.231
opt_global_MS:1002254                                                              0
opt_global_MS:1002255                                                          423.1
opt_global_MS:1002256                                                              1
opt_global_MS:1002257                                                         0.0538
opt_global_MS:1002258                                                             11
opt_global_MS:1002259                                                             16
opt_global_num_matched_peptides                                                61220
opt_global_protein_references                                                 unique
opt_global_target_decoy                                                       target
```

**Comment by Leon-Bichmann** [comment]
Ok, I see so you are running the steps of the pipeline individually until step 12?

I guess it should be the search_engine_score[1] column then and yes I think it is probably the IDFilter step that filters by a certain q-value treshold.

**Comment by Leon-Bichmann** [comment]
#118
