### ISSUE TITLE
Problem with step 11, run Percolator

### ISSUE THREAD

**Issue by HeshamElAbd** [nf-core/mhcquant#140]
I would like to thank the team for the amazing work and the great software, however, I have tried to run the pipeline, everything went well, until step 11 where execution ends with the following error: 
"""
Error executing process > 'run_percolator (1)'

Caused by:
  Process `run_percolator (1)` terminated with an error exit status (8)

Command executed:

  OMP_NUM_THREADS=6 \
  PercolatorAdapter -in s1_all_ids_merged_psm.idXML \
                     -out s1_all_ids_merged_psm_perc.idXML \
                     -seed 4711 \
                     -trainFDR 0.05 \
                     -testFDR 0.05 \
                     -threads 6 \
                     -enzyme no_enzyme \
                     -peptide-level-fdrs \
                     -subset-max-train 0 \
                     -doc 0 \

Command exit status:
  8

Command output:
  Loading input file: s1_all_ids_merged_psm.idXML
  Merging peptide ids.
  Merging protein ids.
  Error: Unexpected internal error (Prefix of string '6file=4959' successfully converted to an integer value. Additional characters found at position 2)

Command wrapper:
  Loading input file: s1_all_ids_merged_psm.idXML
  Merging peptide ids.
  Merging protein ids.
  Error: Unexpected internal error (Prefix of string '6file=4959' successfully converted to an integer value. Additional characters found at position 2)
""" 
I have tried to run the PercolatorAdapter from the openMS docker container with the s1_all_ids_merged_psm.idXML in he intermediate results also ending up in the same results. 

I would truly appreciate your help, thanks a lot

**Comment by Leon-Bichmann** [comment]
Hi @HeshamElAbd,

Thanks for trying MHCquant!
I never encountered this issue before. What kind of MS instrument are you using? Or do you have some special symbols in the filename by any chance?

Feel free to take this conversation to the #mhcquant channel in the nf-core slack: https://nf-co.re/join

**Comment by HeshamElAbd** [comment]
Hi @Leon-Bichmann 
Thank you very much for the great software and thanks a lot for your help. 
Okay, that is interesting, so for the type of machine, it. The file name is made from ASCII chars. At first, I used the mzML files, but then comet throws an error that the file is not indexed, so I used the following command to index the file using openMS FileFilter -peak_options:indexed_file true -in inputfile_.mzML -out_.mzML. 

I re-started the pipeline with the indexed file everything went well until the percolator step, so I am really puzzled by the error, I will try it with different experiments and see the results. Also, I will move the message to MHCquant as well.

**Comment by HeshamElAbd** [comment]
Although we did not figure out the cause of the problem we suspect it is something related to file indexing and working with an unindexed mzML file. Nevertheless, this problem can be resolved by using .raw files directly, i.e. letting the pipeline do the conversion implicitly.
