### ISSUE TITLE
Problem with Mhcquant

### ISSUE THREAD

**Issue by Presta-hub** [nf-core/mhcquant#157]
Hi, I'm trying to use mhcquant with workflow docker profile but when I try to star the pipeline appears this error message:
WARN: unknown format for entry /Users/presta/null in provided sample sheet. ignoring line.
Someone could help me?
Thank you

**Comment by Zethson** [comment]
Hi,

@Presta-hub could you please paste your sample sheet here?

Cheers

**Comment by Leon-Bichmann** [comment]
also feel free to post questions here: https://nfcore.slack.com/archives/mhcquant

**Comment by Presta-hub** [comment]
I'm using the test data called MHCquant-test-datasets-openmspeptidequant 2; I'm trying even on knime but appears this error message :"No fractions annotated in consensusXML. Assuming unfractionated.
Error: Unexpected internal error (Multiple files in a run, but no id_merge_index in PeptideIdentification found.) occurred 4 times!" with the last mzTabExporter node 
https://forum.knime.com/t/mztabexporter-error-in-mhcquant/29111

**Comment by Leon-Bichmann** [comment]
Please switch to using the nextflow implementation instead, the KNIME workflow is not up-to-date at the moment
