### ISSUE TITLE
Handling the case when no significant hit where found

### ISSUE THREAD

**Issue by steffenlem** [nf-core/mhcquant#246]
### Description of feature

Hi,

currently, when for a sample no significant hits were found, it crashes with the error message:
`It seems that there were no significant hits found for one or more samples.\nPlease consider incrementing the '--fdr_threshold' after removing the work directory or to exclude this sample.`

I think we should provide the option to skip the sample and continue. For me, it would make sense if the pipeline printws a warning and simply generated an empty output file for that sample, without stopping.

With the current behavior, the pipeline would constantly crash if we analyzed very large datasets with setting differing from the default ones.
e.g.: providing some custom reference proteome to analyze a large dataset would make the pipeline crash constantly, even if in this case it was expected that multiple samples did not yield any significant hits.

**Comment by jonasscheid** [comment]
Addressed in https://github.com/OpenMS/OpenMS/pull/6698
