### ISSUE TITLE
"No significant hits found" message (dev branch)

### ISSUE THREAD

**Issue by steffenlem** [nf-core/mhcquant#305]
### Description of the bug

When there are no significant hits after FDR filtering, the metadata of the file so no longer printed. The output prints "null" for the sample metadata. This was seen on the current dev branch.

https://github.com/nf-core/mhcquant/blob/840d4d740eb54fc22c5b526da73b528916311626/workflows/mhcquant.nf#L312

**Comment by jonasscheid** [comment]
Will be adressed soon.
Also an errorStrategy needs to be thought about 'FEATUREFINDERUNLABELEDKD' if not enough hits reach LOQ
