### ISSUE TITLE
Remove second environment

### ISSUE THREAD

**Issue by apeltzer** [nf-core/mhcquant#34]
Hi @Leon-Bichmann !

we need to get all tools in a single environment, thus need to recompile all tools required by this pipeline against the most current CXX environment in bioconda/conda-forge. Can you start listing up tools in here, then we could for example start coming up with a strategy on how to achieve this? 

This second environment causes so many downstream issues, that we should get rid of this asap:
- Nextflow Conda environment support is broken this way
- Reproducibility for users is quite difficult, as they need two environments set up

.... 

We should get this rolling for 1.3.X already...

**Comment by apeltzer** [comment]
@Zethson and I had a look at a lot of things and its seriously difficult to debug these things. It looks like there are competing libraries/headers that interfere with each other, thus breaking in certain environments. We need to build two containers for this pipeline:

- one for environment #1 
- one for environment #2 

Have a look at [nf-core/rnafusion](https://github.com/nf-core/rnafusion)!

**Comment by apeltzer** [comment]
Not sure actually @Zethson ?

**Comment by Zethson** [comment]
I did not yet have time to work on this.
Possibly after my exams...

**Comment by Leon-Bichmann** [comment]
#120

**Comment by Leon-Bichmann** [comment]
Alright, just tested with OpenMS 2.5. and a few parameter changes its now working with a single environment.

**Comment by Zethson** [comment]
🎉
