### ISSUE TITLE
Experimental design for batches of replicates

### ISSUE THREAD

**Issue by Leon-Bichmann** [nf-core/mhcquant#39]
On the long run it would be nice to have an experimental design file specifying which samples are replicates and that the whole batch can be processed at once.

**Comment by Zethson** [comment]
Possible [reference implementation](https://github.com/cbcrg/kallisto-nf).
I suggest that we use a yaml file. I'll see what I can do.

**Comment by Leon-Bichmann** [comment]
Hey Lukas,
yaml sounds like a good idea, but I think a tab separated exp_design.txt like in the kallisto pipeline would also do and might be easier for some people.

Any solution will do for now however.

**Comment by Leon-Bichmann** [comment]
I think we agreed that this one is out of scope for now and it would be better to submit batches using a wrapper script around the submissions
