### ISSUE TITLE
Use centralized configs

### ISSUE THREAD

**Issue by apeltzer** [nf-core/mhcquant#42]
https://github.com/nf-core/configs !!!

**Comment by apeltzer** [comment]
Need to add this here to the pipeline config to make the release work again:

https://github.com/nf-core/atacseq/blob/master/nextflow.config#L68-L80

**Comment by Zethson** [comment]
@apeltzer 
Am I understanding this correctly, that you just want the following lines:
```
// Load base.config by default for all pipelines
includeConfig 'conf/base.config'

// Load nf-core custom profiles from different Institutions
try {
  includeConfig "${params.custom_config_base}/nfcore_custom.config"
} catch (Exception e) {
  System.err.println("WARNING: Could not load nf-core/config profiles: ${params.custom_config_base}/nfcore_custom.config")
}
```
to be added to the current [mhcquant nextflow.config](https://github.com/nf-core/mhcquant/blob/master/nextflow.config) just before the processes definitions?

**Comment by Zethson** [comment]
Fixed in https://github.com/nf-core/mhcquant/pull/58/files

**Comment by apeltzer** [comment]
Yes all the other configs can go since these are now centrally curated 👍
