### ISSUE TITLE
Warn if alleles which are not supported by MHCFlurry are specified

### ISSUE THREAD

**Issue by Zethson** [nf-core/mhcquant#57]
Hi,

I think that it would be a good idea to warn users if a specific allele or multiple alleles are not supported by MHCFlurry.
I propose that we enable "echo true" for processes: [predict_psms](https://github.com/Leon-Bichmann/MHCquant/blob/master/main.nf#L780) and [predict peptides](https://github.com/Leon-Bichmann/MHCquant/blob/master/main.nf#L1003). I could then adapt the python scripts to print a warning if an unsupported allele was detected.

Alternative 1: Instead of enabling echo we could redirect stdout, but imo this is overkill here.
Alternative 2: We validate the alleles inline in the nextflow script. I think this unnecessarily clutters the nextflow script.

What do you think @Leon-Bichmann ?

**Comment by Leon-Bichmann** [comment]
good idea, that would be a nice addition

**Comment by Zethson** [comment]
https://github.com/nf-core/mhcquant/pull/58
