### ISSUE TITLE
Add Zenodo DOI for release to main README on master

### ISSUE THREAD

**Issue by drpatelh** [nf-core/mhcquant#87]
Would be good to add the Zenodo DOI for the release to the main README of the pipeline in order to make it citable. You will have to do this via a branch pushed to the repo in order to directly update `master`. See PR below for example and file changes:
https://github.com/nf-core/atacseq/pull/38

See https://zenodo.org/record/3359618#.XVZ0bOhKhPY

Web-hooks are already set-up for this repo to have a unique Zenodo DOI generated everytime a new version of the pipeline is released. Would be good to add this in after every release :+1:

**Comment by Zethson** [comment]
We've submitted a paper about MHCquant which is currently under revision. I assume that we'll just use the DOI of the published paper then?

**Comment by drpatelh** [comment]
Its probably best to use both. Maybe include the release Zenodo DOI now and then add a separate `Citation` entry when the paper is eventually published too. Using the Zenodo DOI means researchers can cite each particular release of a pipeline whereas the actual publication will be a more generic citation for the tools and methodology used in the pipeline.
