### ISSUE TITLE
Error in db_search_comet: Profile data provided but centroided MS2 spectra expected

### ISSUE THREAD

**Issue by NikdAK** [nf-core/mhcquant#91]
Hi,
I am trying to run MHCquant but I am getting the following error:

Caused by:   Process db_search_comet (1) terminated with an error exit status (8)
Progress of 'loading chromatogram list':
  -- done [took 0.01 s (CPU), 0.00 s (Wall)] -- 
  Error: Unexpected internal error (Error: Profile data provided but centroided MS2 spectra expected. To enforce processing of the data set the -force flag.)
Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap

The full error log can be found here: [error_log.txt](https://github.com/nf-core/mhcquant/files/3794413/error_log.txt)

Any idea?
Thank you very much!

**Comment by Zethson** [comment]
Dear @NikdAK,

sorry for the late answer. Currently traveling without stable internet access. 
The error suggestst that you are trying to run the pipeline with profile data, but centroided MS2 Spectra data is required.
Could you please verify that you are trying to run the pipeline with centroided MS2 spectra?
The warning can be ignored.

Cheers

**Comment by NikdAK** [comment]
Hi @Zethson,
thank you for the answer!
You are correct, as I noticed I was trying to use profile instead of centroided data.

I am not used to proteomics data, so I tried a very naive approach of just setting ProteoWizard MSConvert filter to MS levels = 2 while converting from raw to mzML. 

Now I get a new error: 
Error executing process > 'db_search_comet (1)'
Caused by:
  Process exceeded running time limit (2h)

The full log can be found here: 
[error_log.txt](https://github.com/nf-core/mhcquant/files/3814756/error_log.txt)

Apparently the timelimit and thread arguments are not handed down to this function. 
My theory now is that my data is now centroided but extremly "overcrowded" due to insufficient cutoffs during the conversion. Therefore the function just takes too long. 
I just do not know what a decent threshold is during the conversion from raw to centroided mzML. 

Any suggestions?
Thank you very much.
Cheers

**Comment by Zethson** [comment]
Hi,

I'm back now :)

1. How large is your raw and your generated mzml file?
2. Would you mind converting the raw into a centroided mzml file using PeakPickerHiRes from OpenMS? 

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PeakPickerHiRes.html

All unpicked peaks are automatically centroided, so you don't need to worry about MS level selection.

Best

**Comment by Zethson** [comment]
Oh, and I forgot. 

There's also a `run_centroidisation` parameter in mhcquant, which automatically does the centroidization for you.

**Comment by NikdAK** [comment]
So I tried running it with run_centroidisation.
(by the way the PeakPickerHiRes function does not use the full input data path but only the basename for -in, I had to move it to the local folder).

Sadly I get the same error (db_search_comet exceeding running time limit). 
The input file is 1.2 GB large, after peak picking 540MB (this is only 1 of 3 replicates).

The command and error log can be found here: [errorlog.txt](https://github.com/nf-core/mhcquant/files/3916137/errorlog.txt)

**Comment by Leon-Bichmann** [comment]
Hi @NikdAK, sorry for taking so long to respond.

MHCquant does not take raw files as input.

Do you have profile data for the ms1 or ms2 level?

You might have to set the flag: --pick_ms_levels  1

**Comment by Leon-Bichmann** [comment]
@NikdAK Raw Files can now be read with the new release 1.4

**Comment by NikdAK** [comment]
Thank you very much for this update!
The reading of the raw file worked just fine.

Sadly I ran into a new error with "link_extracted_features".
I do not want to fill your github with issues, so I will post the error log right here: 
[mhcquant_errorlog.txt](https://github.com/nf-core/mhcquant/files/4387188/mhcquant_errorlog.txt)

**Comment by Leon-Bichmann** [comment]
ah ok no worries, good to know you didn't give up on this yet ^^

I think in this case it is failing because you ran it with a single file.

You can only run it with a set of replicate files.

Also you need to specify the path to those files in quotes for example:

--raw_input --raw_files "data/*.raw"

**Comment by NikdAK** [comment]
The inclusion of raw file processing brought me back.

Anways:
-[nf-core/mhcquant] Pipeline completed successfully      

＼(＾O＾)／

Thank you very much for your help! 
I will probably contact you via email for a last specific question if that is fine.
Cheers
