### ISSUE TITLE
[CI] Travis build doesn't find Java

### ISSUE THREAD

**Issue by Zethson** [nf-core/mhcquant#92]
```
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 is installed

NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:

 JAVA_CMD: /usr/local/lib/jvm/openjdk11/bin/java

 JAVA_HOME: /usr/local/lib/jvm/openjdk11

The command "wget -qO- get.nextflow.io | bash" failed and exited with 1 during .
```

I assume that we need to bump the minimum nextflow version to at least 19.04.0 .

Has been suggested by @ewels on nf-core slack on October 11th.

**Comment by drpatelh** [comment]
Yep. You may as well bump it to `19.10.0` because that's the version in the template now. Also, allows you to use NF tower.

**Comment by Zethson** [comment]
@drpatelh Great, thanks! Will do when I'm back in Europe.

**Comment by Zethson** [comment]
https://github.com/nf-core/mhcquant/pull/96
